#! /bin/sh

# sxhkd (keyboard hotkeys)
pgrep -x sxhkd > /dev/null || sxhkd &

# default configuration for one monitor
bspc monitor -d 1 2 3 4 q w e r

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio       0.5
bspc borderless_monocle      true
bspc config gapless_monocle  true

bspc config focus_follows_pointer true

# polybar
/home/$USER/.config/polybar/launch.sh